export const FETCH_TASKS_START = 'FETCH_TASKS_START'
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS'
export const FETCH_TASKS_ERROR = 'FETCH_TASKS_ERROR'

export const ADD_TASK_START = 'ADD_TASK_START'
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS'
export const ADD_TASK_ERROR = 'ADD_TASK_ERROR'

export const UPDATE_TASK_START = 'UPDATE_TASK_START'
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS'
export const UPDATE_TASK_ERROR = 'UPDATE_TASK_ERROR'

export const DELETE_TASK_START = 'DELETE_TASK_START'
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS'
export const DELETE_TASK_ERROR = 'DELETE_TASK_ERROR'
